name:                toylang
version:             0.1.0.0
github:              "takataka3131/toylang"
license:             BSD3
author:              "taka2"
maintainer:          "taka23131@gmail.com"
copyright:           "2021 taka2"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/takataka3131/toylang#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- llvm-hs-pure
- llvm-hs
- text
- llvm-hs-pretty
- parser-combinators
- containers
- transformers

library:
  source-dirs: src

executables:
  toylang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toylang

tests:
  toylang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toylang
